main:
  - name: 'HOME'
    url: 'https://apx.wilder.wp.computer'
    weight: 1
  - name: 'TMFP'
    url: 'https://tmfp.wilder.wp.computer'
    weight: 2
  - name: 'THI'
    url: 'https://thi.wilder.wp.computer'
    weight: 3
  - name: 'GPD'
    url: 'https://gpd.wilder.wp.computer'
    weight: 4
  - name: 'CONVO'
    url: 'https://convo.wilder.wp.computer'
    weight: 5
  - name: 'âŒ–â˜®'
    url: 'https://go.wilder.wp.computer'
    weight: 6
  - name: 'ğœ”Ã—ğ›¼'
    url: 'https://wxa.wilder.wp.computer'
    weight: 7
  - name: 'BUILD'
    url: 'https://build.wilder.wp.computer'
    weight: 8

